scraper:
  start_date: "2021/04/01"
  end_date: "2025/08/05"
  exclude_months: [12, 1, 2]
  park_ids: [1,2,3]

models:
  crowd-level:
    train:
      model_name: "Chessington-Crowd-Level"
      include_park_id: 3
    inference:
      model_name: "Chessington-Crowd-Level"
      dates: []